site_name: RS3 — Curvature Study
site_description: Étude des rayons de courbure et implications pour a_lat = v^2/r
site_url: https://sebe585.github.io/rs3-study-curvature/
repo_url: https://github.com/SebE585/rs3-study-curvature
repo_name: SebE585/rs3-study-curvature
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top         # barre de nav collante
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - content.action.edit
  icon:
    logo: material/road-variant # changeable par un logo local si vous en avez un
  favicon: assets/img/favicon.png  # placez un favicon ici si vous en avez un

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex: { generic: true }
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SebE585
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sebastienedet/
      name: LinkedIn
  alternate:
    - name: Français
      link: /
      lang: fr

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_full_path: false
            docstring_style: google
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

nav:
  - Accueil: index.md
  - Méthode: method.md
  - Résultats: results.md
  - Comparaisons:
      - Vue rapide: compare_quick.md
      - Appariement local: compare_nearest.md
  - Produit: product.md
  - Jeux de données: datasets.md
  - Reproductibilité: reproducibility.md
  - Paper (aperçu): paper.md